### ISSUE TITLE
老是跑不起来，搞了一下午了，怎么弄啊

### ISSUE THREAD

**Issue by hechuanhua** [mhbseal/blog#11]
输入 http://localhost:3004/admin，提示  网络错误，请稍后重试..，应该是mongo没连上，我看了下moogo都没有请求，其他又没报错什么的
感觉是不是你的依赖包太旧了造成的？
有句这样的提示，不知道有没有用
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

**Comment by mhbseal** [comment]
mongoose提示这个没关系，3点，1看mongodb是否以正确启动，2看apiServer是否正确启动，3看renderServer是否正确启动，具体错误具体排查！
