### ISSUE TITLE
react界面修改后，无法马上看到效果更新

### ISSUE THREAD

**Issue by sevenearly** [mhbseal/blog#13]
fe/src/containers/admin/ArticleList.js 中 添加一列“来源” <th>标题</th><th>来源</th><th>作者</th> 。 发现网站上刷新后，“来源”闪了下又回到原来的版本，修改没有生效。 重新启动 npm start 修改还是没有生效，npm run build.dev后，再 npm start 修改就生效了。 不知道您那边是不是也有这个问题？

**Comment by mhbseal** [comment]
@sevenearly 具体看package.json，npm start执行的是打包后的js，要webpack实时用npm run watch

**Comment by sevenearly** [comment]
谢谢！ 不过用npm run watch 运行，日志是 ==> webpackServer is running on http://localhost:3005， 但是http://localhost:3005, http://localhost:3005/admin  都无法访问。  浏览器得到的结果是 “Cannot GET /“

**Comment by sevenearly** [comment]
好像明白了， 是npm start, npm run watch同时运行，这个意思吧。

**Comment by mhbseal** [comment]
@sevenearly 是的，我描述有误，应该是替换npm run build.dev为npm run watch，再者给你解释一下，npm run build.dev 其实就是webpack打包js到本地，而npm run watch是webpack.server是编译js到内存可以实时更新你的改动！
