### ISSUE TITLE
初始化数据

### ISSUE THREAD

**Issue by lzcmaro** [mhbseal/blog#3]
请问下，没有初始化数据吗？没见这块的说明，好像也没找着。。。

**Comment by fsy0718** [comment]
- npm run dev.noauth  // 启动（初次运行，用此模式，可免登陆进入后台）
- 登陆后台，自行添加数据

**Comment by lzcmaro** [comment]
第一次是使用npm run dev.noauth启动的，但进入/admin时，出现404错误。看控制台和console没有错误输出。。。

**Comment by lzcmaro** [comment]
看到了，后台路径应该是/admin/admin

**Comment by mhbseal** [comment]
目前后台路径是'/admin/',非'/admin',这两天会提交一次代码优化版，会顺带优化下这个！

**Comment by lzcmaro** [comment]
哦，原来这样。。。感觉是要优化下这里。顺便提下，里面的redux devtools的位置切换、隐藏快捷键感觉也要换一下，现在用的是Q、H，这样会导致在表单输入时，这两个字母输入不了，如果开了控制台的话。

**Comment by mhbseal** [comment]
@lzcmaro commit了次code优化，后台路径问题已经解决，redux devtools的快捷键可以在文件/fe/src/containers/DevTools.js中修改
