### ISSUE TITLE
server side的时候，部分接口想做成异步，请问有什么解决办法

### ISSUE THREAD

**Issue by younth** [mhbseal/blog#4]
RT,大量list的时候，同步渲染想做成部分接口同步，部分异步

**Comment by mhbseal** [comment]
@younth 不管server还是client，异步可以放在componentDidMount里面执行。
另外我这边blog用react、redux同构是参考https://github.com/erikras/react-redux-universal-hot-example ，API: connectData(fetchData，fetchDataDeferred)，但是这个在server端还是等到fetchData，fetchDataDeferred完成了，才返回html给客户端，但是在client端，fetchData同步，fetchDataDeferred异步，但是感觉这个不是很实用！
