### ISSUE TITLE
blog/fe/src/containers/Article.js中的组件事件为什么都要bind一下

### ISSUE THREAD

**Issue by topcatv** [mhbseal/blog#5]
Hi,  我看到在文件`blog/fe/src/containers/Article.js`中的第78行

`this.handleReply.bind(this, comment.user && comment.user.name || comment.admin && comment.admin.name)`

这里为什么要bind一下，react0.4以后的版本不是就可以autobind了吗？
我试了一下改成普通的，那么在handleReply方法体里this就是一个null。

**我想问一下这里为什么要这样写，是因为用了react-redux造成的吗？**

求解释，十分感谢！

**Comment by younth** [comment]
export default class AdminList extends Component  如果继承Component不会自动autobind，你说的autobind是createClass的时候

**Comment by topcatv** [comment]
感谢指教！
确实，在`src/isomorphic/modern/class/ReactComponent.js`文件里没有看到自动绑定的代码，而在它的`src/isomorphic/classic/class/ReactClass.js`文件的762行看到了

``` javascript
// Wire up auto-binding
  if (this.__reactAutoBindPairs.length) {
  bindAutoBindMethods(this);
}
.....
/**
 * Binds all auto-bound methods in a component.
 *
 * @param {object} component Component whose method is going to be bound.
 */
function bindAutoBindMethods(component) {
  var pairs = component.__reactAutoBindPairs;
  for (var i = 0; i < pairs.length; i += 2) {
    var autoBindKey = pairs[i];
    var method = pairs[i + 1];
    component[autoBindKey] = bindAutoBindMethod(
      component,
      method
    );
  }
}
```
