### ISSUE TITLE
npm run dev.noauth 后访问不了后台

### ISSUE THREAD

**Issue by terryvi** [mhbseal/blog#8]
你好：
       根据readme里边的步骤 最后一步开了npm run dev.noauth 后访问http://localhost:3004/admin，提示localhost 拒绝了我们的连接请求。我看mongodb 那边应该是也是运行了的，因为运行npm run dev.noauth的时候有连接的提示：[initandlisten] connection accepted from 127.0.0.1:51482 #2 (1 connection now open)。 
控制台并没有报任何错误

OS： win10 
node:v4.3.0

期待您的回答

**Comment by mhbseal** [comment]
@terryvi win下，npm run dev.noauth这个进package.json中看对应的命令行，分开输入吧，注释了dev，忘记注释这个dev.noauth了，后续有空会写个脚本！

**Comment by terryvi** [comment]
好哒~我一会去试试~thx

**Comment by hechuanhua** [comment]
@mhbseal 怎么分开输入啊，我每个  npm run start.api.noauth & npm run start.render & npm run start.webpack命令都单独试了下，输入http://localhost:3004 还是提示拒绝连接请求啊，输入http://localhost:3003/  就提示 {"status":"warnning","msg":"无此api"}

**Comment by hechuanhua** [comment]
@terryvi 你是怎么解决的，我的也和你一样，但是分开输入也没用啊，还是提示拒绝连接
